name = "query"
repo = ""
commit = ""
license = ""
inventor = "Max Brunsfeld"
year = 2020
description = ""
link = "https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries"
trivia = ""

