name = "erlang"
repo = ""
commit = ""
license = ""
inventor = "Joe Armstrong, Robert Virding, Mike Williams"
year = 1986
description = ""
link = "https://en.wikipedia.org/wiki/Erlang_(programming_language)"
trivia = ""

