name = "dot"
repo = ""
commit = ""
license = ""
inventor = "Stephen North and AT&T Bell Labs"
year = 1991
description = ""
link = "https://en.wikipedia.org/wiki/DOT_(graph_description_language)"
trivia = ""

